### ISSUE TITLE
Gas estimation error

### ISSUE THREAD

**Issue by Maakai123** [PatrickAlphaC/fund-me-fcc#9]
After dividing minimum uds =50 by current price of eth which was 0.05 eth, after converting to wei it did not deploy

Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending?
err: insufficient funds for gas * price + value: address 0x8d511bA6dE98c8ACE13Da5928a25A3D846F79AC3 have 34143617423679513 want 50000000000000000 (supplied gas 15010499)

**Comment by mubashirhussainkhadim** [comment]
This error is common if you don't have enough eth in your account, if your node isn't in sync with the network, or if you don't specify a gas price or something else is slightly wrong with the command. In this case, I'm guessing it was the attacks on the network causing your node not to be 100% in line with reality or timing out or something similar, which is why upgrading fixed it

**Comment by iangechuki** [comment]
@Maakai123 I had an error almost similar to this .I solved it by increasing the amount of wei before clicking the fund button.
Looks like  I wasn't getting the conversion right

**Comment by PatrickAlphaC** [comment]
Closing, feel free to make a discussion in the main repo.
